//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broker.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarInsuranceQuoteRequest
    {
        public int CarQuoteId { get; set; }
        public string CarRegistration { get; set; }
        public string CarMake { get; set; }
        public string CarModel { get; set; }
        public string CarDesc { get; set; }
        public Nullable<int> CarYear { get; set; }
        public Nullable<int> CountyId { get; set; }
        public Nullable<int> NoClaimsDiscountYears { get; set; }
        public Nullable<decimal> VehicleValue { get; set; }
        public Nullable<int> DriverAge { get; set; }
        public string EmailAddress { get; set; }
        public string Telephone { get; set; }
        public Nullable<System.DateTime> UTCDateAdded { get; set; }
    
        public virtual County County { get; set; }
    }
}
