//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broker.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarInsuranceQuoteResponse
    {
        public int ResponseId { get; set; }
        public int CarQuoteId { get; set; }
        public string Insurer { get; set; }
        public string QuoteType { get; set; }
        public Nullable<decimal> QuoteValue { get; set; }
        public Nullable<System.DateTime> UTCDateAdded { get; set; }
        public Nullable<bool> IsCheapest { get; set; }
    
        public virtual CarInsuranceQuoteRequest CarInsuranceQuoteRequest { get; set; }
    }
}
