//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broker.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarInsuranceQuoteRequest
    {
        public CarInsuranceQuoteRequest()
        {
            this.CarInsuranceQuoteResponses = new HashSet<CarInsuranceQuoteResponse>();
        }
    
        public int CarQuoteId { get; set; }
        public int VehicleId { get; set; }
        public Nullable<int> CountyId { get; set; }
        public Nullable<int> NoClaimsDiscountYears { get; set; }
        public Nullable<decimal> VehicleValue { get; set; }
        public Nullable<int> DriverAge { get; set; }
        public string EmailAddress { get; set; }
        public string Telephone { get; set; }
        public Nullable<System.DateTime> UTCDateAdded { get; set; }
    
        public virtual County County { get; set; }
        public virtual VehicleDetail VehicleDetail { get; set; }
        public virtual ICollection<CarInsuranceQuoteResponse> CarInsuranceQuoteResponses { get; set; }
    }
}
