//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broker.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeInsuranceQuoteRequest
    {
        public int HomeQuoteId { get; set; }
        public int InsuranceTypeId { get; set; }
        public Nullable<bool> IsSublet { get; set; }
        public int CountyId { get; set; }
        public int TownId { get; set; }
        public Nullable<int> YearBuilt { get; set; }
        public Nullable<int> NumBedrooms { get; set; }
        public Nullable<decimal> BuildingCover { get; set; }
        public Nullable<decimal> ContentsCover { get; set; }
        public string EmailAddress { get; set; }
        public string Telephone { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> UTCDateAdded { get; set; }
        public Nullable<int> HouseTypeId { get; set; }
    
        public virtual County County { get; set; }
        public virtual HouseType HouseType { get; set; }
        public virtual InsuranceType InsuranceType { get; set; }
        public virtual Town Town { get; set; }
    }
}
