//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broker.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceType
    {
        public InsuranceType()
        {
            this.HomeInsuranceQuoteRequests = new HashSet<HomeInsuranceQuoteRequest>();
        }
    
        public int InsuranceTypeId { get; set; }
        public string InsuranceType1 { get; set; }
        public string InsuranceDesc { get; set; }
        public Nullable<System.DateTime> UTCDateAdded { get; set; }
    
        public virtual ICollection<HomeInsuranceQuoteRequest> HomeInsuranceQuoteRequests { get; set; }
    }
}
