//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broker.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleDetail
    {
        public int VehicleId { get; set; }
        public string ModelName { get; set; }
        public string ModelDesc { get; set; }
        public Nullable<int> ManufYear { get; set; }
        public string CurrentRegistration { get; set; }
        public string Colour { get; set; }
        public string BodyType { get; set; }
        public string FuelType { get; set; }
        public string Transmission { get; set; }
        public Nullable<bool> IsImport { get; set; }
        public Nullable<System.DateTime> UTCDateAdded { get; set; }
    }
}
